/* Resource file indices for CURDLEST. */

#define CURDLE_UI        0   /* Form/Dialog-box */
#define CURDLE_STATUS    1   /* TEXT in tree CURDLE_UI */
#define CURD_GRID        2   /* IBOX in tree CURDLE_UI */
#define CURD_GRID_FIRST  3   /* BOXCHAR in tree CURDLE_UI */
#define CURDLE_KB        33  /* IBOX in tree CURDLE_UI */
#define CURDLE_KB_FIRST  34  /* BOXCHAR in tree CURDLE_UI */

#define CURDLE_STATS     1   /* Form/Dialog-box */
#define STATS_FIRST      2   /* TEXT in tree CURDLE_STATS */
#define STATS_FIRST_BAR  15  /* BOXTEXT in tree CURDLE_STATS */

#define CURDLE_ABOUT     2   /* Form/Dialog-box */
#define ICON_SEG         1   /* ICON in tree CURDLE_ABOUT */
